### ISSUE TITLE
Problem when run with Express

### ISSUE THREAD

**Issue by oniram-reach** [HubSpot/calling-extensions-sdk#53]
I need run this sdk with express, but i give this error:

ReferenceError: window is not defined
    at Object.<anonymous> (../node_modules/@hubspot/calling-extensions-sdk/dist/main.js:10:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/oniram/workspace/teste/index.js:3:29)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)

**Comment by dstgermain** [comment]
This is a client side SDK for iframe communication. It's not usable in node.
